### ISSUE TITLE
Unable to run `ansible-playbook -v playbooks/documentation-archive-prepare.yml` on MacBook Pro M3

### ISSUE THREAD

**Issue by mraible** [jhipster/jhipster-ansible#9]
<img width="1468" alt="Screenshot 2024-04-09 at 1 53 30 PM" src="https://github.com/jhipster/jhipster-ansible/assets/17892/8a113ad1-d213-4515-a287-2a271230b9e6">

If I look in Docker Desktop, you can see the error:

<img width="1444" alt="Screenshot 2024-04-09 at 1 54 09 PM" src="https://github.com/jhipster/jhipster-ansible/assets/17892/0e11f438-5b4e-460a-a2a2-ecc85b2ede07">

```
2024-04-09 13:53:06 ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
2024-04-09 13:53:06             Source: /srv/jekyll
2024-04-09 13:53:06        Destination: /srv/jekyll/_site
2024-04-09 13:53:06  Incremental build: disabled. Enable with --incremental
2024-04-09 13:53:06       Generating... 
2024-04-09 13:53:06                     done in 0.009 seconds.
2024-04-09 13:53:07  Auto-regeneration: enabled for '/srv/jekyll'
2024-04-09 13:53:06 Configuration file: none
2024-04-09 13:53:07                     ------------------------------------------------
2024-04-09 13:53:07       Jekyll 4.2.2   Please append `--trace` to the `serve` command 
2024-04-09 13:53:07                      for any additional information or backtrace. 
2024-04-09 13:53:07                     ------------------------------------------------
2024-04-09 13:53:07 <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- webrick (LoadError)
2024-04-09 13:53:07     from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2024-04-09 13:53:07     from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
2024-04-09 13:53:07     from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `require_relative'
2024-04-09 13:53:07     from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `setup'
2024-04-09 13:53:07     from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:100:in `process'
2024-04-09 13:53:07     from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
2024-04-09 13:53:07     from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
2024-04-09 13:53:07     from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
2024-04-09 13:53:07     from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
2024-04-09 13:53:07     from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
2024-04-09 13:53:07     from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
2024-04-09 13:53:07     from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
2024-04-09 13:53:07     from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
2024-04-09 13:53:07     from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
2024-04-09 13:53:07     from /usr/gem/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
2024-04-09 13:53:07     from /usr/gem/bin/jekyll:25:in `load'
2024-04-09 13:53:07     from /usr/gem/bin/jekyll:25:in `<main>'
```

**Comment by deepu105** [comment]
This step works fine for me. What happens if you run bundle install on jhipster.github.io project?

**Comment by deepu105** [comment]
I have jekyll 3.9.3 and ruby/3.1.0

**Comment by deepu105** [comment]
I might have found the issue. Let me see if I can fix it

**Comment by deepu105** [comment]
The original gemfile has webrick in it so no need to create a newfile

**Comment by mraible** [comment]
If I clone the jhipster.github.io repo and run `bundle install`, it succeeds. However, when I run `npm start`, it fails with the following error:

```
Dependency Error: Yikes! It looks like you don't have jemoji or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- nokogiri/nokogiri' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
jekyll 3.9.5 | Error:  jemoji
```

My version of Ruby on my new M3:

```
$ ruby --version
ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
```

**Comment by mraible** [comment]
I tried upgrading to Ruby 3 with `brew install ruby`, but it still uses `/usr/bin/ruby` and I can't delete it with `sudo rm /usr/bin/ruby`. 

```
override r-xr-xr-x root/wheel restricted,compressed for /usr/bin/ruby? y
rm: /usr/bin/ruby: Operation not permitted
```
